### ISSUE TITLE
Incorrect IFS value

### ISSUE THREAD

**Issue by shrivara** [Shippable/execTemplates#19]
We're setting the value of IFS to `$'\n\t'` here:
https://github.com/Shippable/execTemplates/blob/3886c57ab86ff5da1ed794d7f4e0f5383da8943a/integrations/common/_helpers.sh#L3

This causes weird issues in our scripts because only new-lines and tabs are considered as word delimiters and not spaces.

The default value for IFS in bash scripts actually contains a space(plus new line and tab). We should change the value of IFS to include a space:
```shell
IFS=$' \t\n'
```

---
To illustrate the difference, open a bash shell and run the following:
```shell
$ IFS=$'\t\n'
$ cmd="ls -la"
$ $cmd
ls -la: command not found

$ IFS=$' \t\n'
$ cmd="ls -la"
$ $cmd
test_ifs
```

https://github.com/Shippable/pm/issues/8957

**Comment by shrivara** [comment]
@ric03uec, we'll be fixing this as we ran into this problem in a couple of places. We should probably fix this is in Admiral too, but we'll wait for you comment on this before that.

**Comment by scriptnull** [comment]
Verified this change in RC. It seems to be working.
